default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: railsuser
  password: yuukunndaisuki
  socket: /tmp/mysql.sock

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mybbs_development
  pool: 5
  username: railsuser
  password: yuukunndaisuki
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mybbs_test
  pool: 5
  username: railsuser
  password: yuukunndaisuki
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mybbs_production
  pool: 5
  username: railsuser
  password: yuukunndaisuki
  host: localhost

